name: reactive_exploration
description: Reactive Flutter apps

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

environment:
  sdk: "^3.1.0"
